package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPasswordDao;
import com.miaoshaproject.dataobject.UserPasswordDaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    long countByExample(UserPasswordDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int deleteByExample(UserPasswordDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    List<UserPasswordDao> selectByExample(UserPasswordDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    UserPasswordDao selectByPrimaryKey(Integer id);


    UserPasswordDao selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPasswordDao record, @Param("example") UserPasswordDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int updateByExample(@Param("record") UserPasswordDao record, @Param("example") UserPasswordDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jul 06 14:16:19 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDao record);
}